### ISSUE TITLE
Please update the world-cup Scores!!!

### ISSUE THREAD

**Issue by kiwi-koder** [openfootball/world-cup.json#10]
My company is relying on it for our sweepstakes!!

**Comment by ralphbk** [comment]
I was too, but now I've rewritten my code to use http://worldcup.sfg.io/matches instead.

**Comment by geraldb** [comment]
Why not help update the scores? Yes, YOU! Yes, you can. See <https://github.com/openfootball/world-cup.json/issues/7>.

**Comment by JPolacek** [comment]
I'm confused. You're telling us to update the scores ourselves but #7 says not to modify the JSON, which is what needs to be updated.

**Comment by geraldb** [comment]
It says it in the README. Please update the (plain) source text e.g. cup.txt (and NOT the generated JSON files - they will get overwritten with every update).  Learn more about the football.db @ <http://openfootball.github.io/>.
