### ISSUE TITLE
Position for teams on same points do not reflect FIFA group results

### ISSUE THREAD

**Issue by ht2** [openfootball/world-cup.json#5]
The dataset currently has Spain as `pos: 2` and Portugal as `pos: 3` in Group B.

Looking at the official FIFA site (https://www.fifa.com/worldcup/groups/) and other organisations such as BBC, ESPN, they all seem to have Portugal as 2 and Spain as 3.

It would be useful to reflect the public facing version of the group results if possible.

_As far as I can tell, the actual rules for tiebreakers seem to be the following:_ 

* Goal difference in all group matches
* Goals scored in all group matches
* Head-to-head points between the teams concerned
* Goal difference in the group matches between the teams concerned
* Goals scored in group matches between the teams concerned
* Points obtained in fair play conduct *(yellow cards = -1, indirect red card = -3, direct red card = -4, yellow card and direct red = -5)
* Drawing of lots by the FIFA Organising Committee

**Comment by geraldb** [comment]
You're welcome to contribute. Where or when do you want to start? Why not introduce yourself at the forum / mailinglist?
