### ISSUE TITLE
Repeated match dates

### ISSUE THREAD

**Issue by asunar** [openfootball/world-cup.json#6]
Have you considered moving match date one level up to the match day level? All the matches on the same match day have the same dates. That may remove some duplicate dates.

![image](https://user-images.githubusercontent.com/204049/41504404-bc4822d8-71b3-11e8-8056-77734b1c2c98.png)

**Comment by geraldb** [comment]
The names of the teams are also duplicates. If you want to contribute, you're more than welcome.  Why not introduce yourself at the forum / mailinglist?
