### ISSUE TITLE
Latest Match Results / Missing - Please, Update

### ISSUE THREAD

**Issue by geraldb** [openfootball/world-cup.json#7]
FYI: I am just a random nobody - there's no budget and no time - what do you expect what I can do for you today?

You're more than welcome to help out and contribute.  A good first start would be helping with match results / updates. To quote from the README:

## Updates / Contributions Welcome - Please Update the Source Text Files

Note: The JSON files get (auto-)generated using the football.db datasets, thus, **please do NOT
edit the JSON files but the source text files in the world cup (and friends) repos** e.g.:

- World Cups in [`/world-cup`](https://github.com/openfootball/world-cup)
- National Teams in [`/national-teams`](https://github.com/openfootball/national-teams)
- Stadiums in [`/stadiums`](https://github.com/openfootball/stadiums)
- and so on

Note: For the World Cup 2018 please update the source text file
[`/world-cup/2018--russia/cup.txt`](https://github.com/openfootball/world-cup/blob/master/2018--russia/cup.txt) for the group stage and
[`/world-cup/2018--russia/cup_finals.txt`](https://github.com/openfootball/world-cup/blob/master/2018--russia/cup_finals.txt) for the knockout (quarter-finals, semi-finals, etc.) stage.

**Comment by larkov** [comment]
cup.txt is updated with Matchday 3 results but the json file hasn't been updated yet. When does it (auto)generate?

**Comment by mikizuk** [comment]
Hello, I would like to update the data, but I can't understand where I can find source text file. Please explain and I will happy to contribute.

**Comment by geraldb** [comment]
See above (as copied from the [README](https://github.com/openfootball/world-cup.json)) and for your convenience once more:

> Note: For the World Cup 2018 please update the source text file
[`/world-cup/2018--russia/cup.txt`](https://github.com/openfootball/world-cup/blob/master/2018--russia/cup.txt) for the group stage and
[`/world-cup/2018--russia/cup_finals.txt`](https://github.com/openfootball/world-cup/blob/master/2018--russia/cup_finals.txt) for the knockout (quarter-finals, semi-finals, etc.) stage.

And from the [F.A.Q. docu page](http://openfootball.github.io/docs/questions#q-how-can-i-contribute--update-match-scores-schedules-leagues-etc):

#### Q: How can I contribute / update match scores, schedules, leagues, etc.?

A: Your contributions are welcome. It works like a wiki, that is, the datasets are plain text documents that anybody can update (if you're an openfootball team member - you can update it directly in your browser or push your commits; otherwise you may use a pull request).

For example, to add the result for the Brazil vs Croatia match:

```
Thu Jun/12 17:00   Brazil  vs  Croatia
```

change the line to:

```
Thu Jun/12 17:00   Brazil  3-1 (1-1)  Croatia
```

Bonus: Let's add the goal getters too. Example:

```
Thu Jun/12 17:00   Brazil  3-1 (1-1)  Croatia
                     [Neymar 29', 71' (pen.) Oscar 90+1';  Marcelo 11' (o.g.)]
```

That's it.

**Comment by geraldb** [comment]
Thanks for the updates. Congrats to France. See you all in 2022.
