### ISSUE TITLE
Latest match days missing

### ISSUE THREAD

**Issue by JPolacek** [openfootball/world-cup.json#9]
Matches for England v. Panama, Senegal v. Japan, Colombia v. Poland, Russia v. Uruguay, Egypt v. Saudi Arabi, Portugal v. Iran, and Spain v. Morocco are missing.

For record, those scores are:
England 6 - 1 Panama
Senegal 2 - 2 Japan
Colombia 3 - 0 Poland
Russia 1 - 3 Uruguay
Egypt 1 - 2 Saudi Arabi
Portugal 1 - 1 Iran
Spain 2 - 2 Morocco

**Comment by kingstakh** [comment]
Looks like we were framed. Data is not updated or updated but extremely rare. It is necessary to correct manually, this is very bad

**Comment by larkov** [comment]
This is a community effort. Please read issue #7 for more information.

Q: What’s the update frequency of the datasets?
A: It’s an open source (public domain) volunteer effort. Datasets get updated when they get updated, that is, there’s no schedule and no guarantee. If you need updates today you have at least two options:

Option 1) Contribute your updates to the datasets.
Option 2) Clone the datasets and update your own private or public copies yourself.

**Comment by kingstakh** [comment]
Hm, what about:

> Automate, Automate, Automate
If all works (almost) daily updates get pushed by yorobot. See the yorobot/football.db build scripts for the (auto-)update machinery.

**Comment by geraldb** [comment]
See <https://github.com/openfootball/world-cup.json/issues/7> on how to help to update the scores. There no magic robot for step one (updating the scores in cup.txt). Why not help to update the scores? Yes, YOU! Yes, you can. Big thank you to Lari Kovanen  for helping with updating the World Cup 2018.

**Comment by JPolacek** [comment]
I'm sorry, I was confused because I've been using the JSON and I could have sworn the README said not to manually change the JSON.

**Comment by geraldb** [comment]
FYI: It says it in the README. Please update the (plain) source text e.g. cup.txt (and NOT the generated JSON files - they will get overwritten with every update).  Learn more about the football.db @ <http://openfootball.github.io/>.
